makefile

diff --git a/tools/st b/tools/st
--- a/tools/st
+++ b/tools/st
@@ -1,9 +1,10 @@
 #!/bin/bash
 version_upgrade="0.0.0.1"
+version_path="./version.txt"
 
 upgrade_version() {
     addition=$1
-    version=`cat ./version.txt`
+    version=`cat $version_path`
     segs=(${version//./ })
     if [ ${#segs[@]} -ne 4 ]; then
         echo -e "Invalid version.txt format"
@@ -31,7 +32,7 @@ upgrade_version() {
     patch=`expr $patch + $patch_add`
     build=`expr $build + $build_add`
 
-    echo "$primary.$secondary.$patch.$build" > ./version.txt
+    echo "$primary.$secondary.$patch.$build" > $version_path
 }
 
 if [ "$#" -ne "4" ]; then
@@ -49,8 +50,12 @@ while [ $# -ge 2 ] ; do
 done
 
 if [ ! -f ./version.txt ]; then
-    echo -e "Cannot find version.txt"
-    exit 1
+    if [ ! -f ./src/version.txt ]; then
+        echo -e "Cannot find version.txt"
+        exit 1
+    else
+        version_path="./src/version.txt"
+    fi
 fi
 
 upgrade_version $version_upgrade
@@ -61,6 +66,7 @@ git add $modified_files
 git commit -m "$comment"
 git push
 
-new_version=`cat ./version.txt`
+new_version=`cat $version_path`
 git tag -a $new_version -m "$comment"
 git push --tags
+
