upgrade

diff --git a/tools/vmt b/tools/vmt
--- a/tools/vmt
+++ b/tools/vmt
@@ -2,9 +2,9 @@
 #Vspace Manufacture Tool
 username=`id -un`
 projectroot="/home/$username/project"
-marapubpath="/data/x/tools/mara-pub"
+vpcmpath="$GOPATH/vpcm"
 token=`cat /proc/sys/kernel/random/uuid`
-toberestarted_projects=""
+toberestarted_plans=""
 is_restartting="no"
 
 publish_project() {
@@ -15,24 +15,6 @@ publish_project() {
     planname=$5
     tag=$6
     
-    local_serviceroot=""
-    local_serviceuser=""
-    local_servicegroup=""
-    
-    if [ -f $GOPATH/vpcm/environment/$destnation/project/$projectname/publish/service_user.env ]; then 
-        local_serviceuser=`cat $GOPATH/vpcm/environment/$destnation/project/$projectname/publish/service_user.env`
-    fi
-    if [ -f $GOPATH/vpcm/environment/$destnation/project/$projectname/publish/service_group.env ]; then 
-        local_servicegroup=`cat $GOPATH/vpcm/environment/$destnation/project/$projectname/publish/service_group.env`
-    fi
-    
-    if [ "$local_serviceuser" == "" ]; then
-        local_serviceuser=$serviceuser
-    fi
-    if [ "$local_servicegroup" == "" ]; then
-        local_servicegroup=$servicegroup
-    fi
-    
     if [ "$is_restartting" == "no" ];then
         cd $GOPATH/target/$destnation
         tar -czf $projectname.tar.gz $projectname/$tag/
@@ -40,37 +22,18 @@ publish_project() {
         ssh -p $port -qt $username@$hostname "cd $projectroot; tar -xf $projectroot/$projectname.tar.gz; rm -f $projectroot/$projectname.tar.gz"
     fi
 
-    local_serviceroot=""
-    before_cmd=""
-    after_cmd==""
-    export_path=""
-    related_projects=""
-
-    if [ -d $marapubpath/projects/$planname ]; then
-        local_serviceroot=`publoader -e $environment -i $marapubpath -p $planname -s deploy`
-        before_cmd=`publoader -e $environment -i $marapubpath -p $planname -s before`
-        after_cmd=`publoader -e $environment -i $marapubpath -p $planname -s after`
-        export_path=`publoader -e $environment -i $marapubpath -p $planname -s exportpath`
-        related_projects=`publoader -e $environment -i $marapubpath -p $planname -s related_project`
+    if [ -f $vpcmpath/$destnation/plan/$planname/publish.yml ]; then
+        local_serviceroot=`configloader -i $vpcmpath/$destnation/plan/$planname/publish.yml -s deploy`
+        local_servicegroup=`configloader -i $vpcmpath/$destnation/plan/$planname/publish.yml -s service_group`
+        local_serviceuser=`configloader -i $vpcmpath/$destnation/plan/$planname/publish.yml -s service_user`
+        before_cmd=`configloader -i $vpcmpath/$destnation/plan/$planname/publish.yml -s before`
+        after_cmd=`configloader -i $vpcmpath/$destnation/plan/$planname/publish.yml -s after`
+        related_plan=`configloader -i $vpcmpath/$destnation/plan/$planname/publish.yml -s related_project`
     else
-        if [ -f $GOPATH/vpcm/environment/$destnation/project/$projectname/$planname.serviceroot ]; then 
-            local_serviceroot=`cat $GOPATH/vpcm/environment/$destnation/project/$projectname/$planname.serviceroot` 
-        fi
-        if [ -f $GOPATH/vpcm/environment/$destnation/project/$projectname/$planname.before ]; then
-            before_cmd=`cat $GOPATH/vpcm/environment/$destnation/project/$projectname/$planname.before`
-        fi
-        if [ -f $GOPATH/vpcm/environment/$destnation/project/$projectname/$planname.after ]; then
-            after_cmd=`cat $GOPATH/vpcm/environment/$destnation/project/$projectname/$planname.after`
-        fi
-        if [ -f $GOPATH/vpcm/environment/$destnation/project/$projectname/$planname.export_path ]; then
-            export_path=`cat $GOPATH/vpcm/environment/$destnation/project/$projectname/$planname.export_path`
-        fi
-        if [ -f $GOPATH/vpcm/environment/$destnation/project/$projectname/$planname.related ]; then
-            related_projects=`cat $GOPATH/vpcm/environment/$destnation/project/$projectname/$planname.related`
-        fi
+        echo -e "\033[31mPublish project failed: Cannot find $vpcmpath/$destnation/plan/$planname/publish.yml\033[0m"
+        exit 1
     fi
 
-    #Before publishing, do something compliable with rigger
     if [ "$before_cmd" != "" ]; then
         echo "Calling $projectname - $planname - before: [$before_cmd]"
         ssh -p $port -qt $username@$hostname "if [ -d $local_serviceroot/$projectname ]; then cd $local_serviceroot/$projectname; sudo $before_cmd; fi"
@@ -79,10 +42,9 @@ publish_project() {
     if [ "$is_restartting" == "no" ];then
         #Do publishing
         ssh -p $port -qt $username@$hostname "sudo bash $projectroot/$projectname/$tag/vasc_init.sh \"$local_serviceroot\" \"$local_serviceuser\" \"$local_servicegroup\" \"$projectname\" \"$export_path\" \"$tag\" \"$environment\" \"$token\""
-        toberestarted_projects="$toberestarted_projects $related_projects"
+        toberestarted_plans="$toberestarted_plans $related_plan"
     fi
-    
-    #After publishing, compatible with rigger
+   
     if [ "$after_cmd" != "" ]; then
         echo "Calling $projectname - $planname - after: [$after_cmd]"
         ssh -p $port -qt $username@$hostname "cd $local_serviceroot/$projectname; sudo $after_cmd"
@@ -91,18 +53,21 @@ publish_project() {
     rm -f $projectname.tar.gz
 }
 
-restart_project() {
+restart_plan() {
     hostname=$1
     port=$2
     username=$3
     
     #Restart related projects
     is_restartting="yes"
-    if [ "$toberestarted_projects" != "" ];then
-        for related_project in $toberestarted_projects
+    if [ "$toberestarted_plans" != "" ];then
+        for related_plan in $toberestarted_plans
         do
-            echo -e "\033[35mRestarting $related_project...\033[0m"
-            publish_project $hostname $port $username $related_project $related_project 
+            echo -e "\033[35mRestarting $related_plan...\033[0m"
+            related_project = `configloader -i $vpcmpath/$environment/plan/$related_plan/publish.yml -s project_name`
+            if [ "$related_project" @= "" ];then
+                publish_project $hostname $port $username $related_project $related_plan
+            fi
         done
     fi
     is_restartting="no"
@@ -163,48 +128,12 @@ if [ "$action" == "" ]; then
 fi
 
 if [ "$destnation" == "" ]; then
-        echo -e "\033[31mFailed: environment cannot be empty\033[0m"
-        exit 1   
-fi
-    
-if [ ! -f $GOPATH/vpcm/environment/$destnation/global/service_root.env ]; then
-        echo -e "\033[31mPublishing failed: cannot find $GOPATH/vpcm/environment/$destnation/global/service_root.env\033[0m"
-        exit 1
-fi
-serviceroot=`cat $GOPATH/vpcm/environment/$destnation/global/service_root.env`
-if [ "$serviceroot" == "" ]; then
-    echo -e "\033[31mPublishing failed: cannot find any content in $GOPATH/vpcm/environment/$destnation/global/service_root.env\033[0m"
-    exit 1
+    echo -e "\033[31mFailed: environment cannot be empty\033[0m"
+    exit 1   
 fi
 
-if [ ! -f $GOPATH/vpcm/environment/$destnation/global/service_user.env ]; then
-    echo -e "\033[31mPublishing failed: cannot find $GOPATH/vpcm/environment/$destnation/global/service_user.env\033[0m"
-    exit 1
-fi
-serviceuser=`cat $GOPATH/vpcm/environment/$destnation/global/service_user.env`
-if [ "$serviceuser" == "" ]; then
-    echo -e "\033[31mPublishing failed: cannot find any content in $GOPATH/vpcm/environment/$destnation/global/service_user.env\033[0m"
-    exit 1
-fi
-
-if [ ! -f $GOPATH/vpcm/environment/$destnation/global/service_group.env ]; then
-    echo -e "\033[31mPublishing failed: cannot find $GOPATH/vpcm/environment/$destnation/global/service_group.env\033[0m"
-    exit 1
-fi
-servicegroup=`cat $GOPATH/vpcm/environment/$destnation/global/service_group.env`
-if [ "$servicegroup" == "" ]; then
-    echo -e "\033[31mPublishing failed: cannot find any content in $GOPATH/vpcm/environment/$destnation/global/service_group.env\033[0m"
-    exit 1
-fi
-if [ ! -f $GOPATH/vpcm/environment/$destnation/global/environment.env ]; then
-    echo -e "\033[31mPublishing failed: cannot find $GOPATH/vpcm/environment/$destnation/global/environment.env\033[0m"
-    exit 1
-fi
-environment=`cat $GOPATH/vpcm/environment/$destnation/global/environment.env`
-if [ "$environment" == "" ]; then
-    echo -e "\033[31mPublishing failed: cannot find any content in $GOPATH/vpcm/environment/$destnation/global/environment.env\033[0m"
-    exit 1
-fi
+environment=$destnation
+serviceroot=`cat $GOPATH/vpcm/$destnation/service_root.scm`
 
 cwd=`pwd`
 
@@ -287,7 +216,7 @@ if [ "$action" == "generate" ]; then
             echo "$projectname" >> $GOPATH/unstamped.txt
         fi
         echo "$projectname/$tag" >> $GOPATH/baseline/$newbaseline
-    done < $GOPATH/vpcm/environment/$destnation/global/project_list.scm
+    done < $GOPATH/vpcm/$destnation/project_list.scm
 
     unstamped_project=`cat $GOPATH/unstamped.txt`
     rm -f $GOPATH/unstamped.txt
@@ -314,7 +243,7 @@ fi
 if [ "$action" == "pubproject" ]; then
     projectname=`basename \`pwd\``
     
-    project_exist=`grep -E "^$projectname " $GOPATH/vpcm/environment/$destnation/global/project_list.scm`
+    project_exist=`grep -E "^$projectname " $GOPATH/vpcm/$destnation/project_list.scm`
     if [ "$project_exist" == "" ]; then
         echo -e "\033[31mCannot find $projectname in project list!\033[0m"
         exit 1
@@ -372,7 +301,7 @@ if [ "$action" == "publish" ]; then
         fi
     done
     
-    hostlist=`cat $GOPATH/vpcm/environment/$destnation/global/host_list.scm`
+    hostlist=`cat $GOPATH/vpcm/$destnation/host_list.scm`
     for hostline in $hostlist
     do
         hostname=${hostline%%:*}
@@ -401,28 +330,25 @@ if [ "$action" == "publish" ]; then
             projectname=${line%%/*}
             compare="0"
             
-            need_publish=`grep -E "^$projectname " $GOPATH/vpcm/environment/$destnation/global/project_list.scm | awk '{ print $4; }'`
-            plan_list=`grep -E "^$projectname " $GOPATH/vpcm/environment/$destnation/global/project_list.scm | awk '{ print $5; }'`
+            need_publish=`grep -E "^$projectname " $GOPATH/vpcm/$destnation/project_list.scm | awk '{ print $4; }'`
+            plan_list=`grep -E "^$projectname " $GOPATH/vpcm/$destnation/project_list.scm | awk '{ print $5; }'`
             
             if [ "$need_publish" != "yes" ]; then
                 continue
             fi
+            
+            OLD_IFS="$IFS"
+            IFS=","
+            arr=($plan_list)
+            IFS="$OLD_IFS"
+                
             if [ "$publish_option" == "all" ]; then
                 echo -e "\033[33mForce publishing $projectname: $tag\033[0m"
-                if [ ! -f $GOPATH/vpcm/environment/$destnation/project/$projectname/plan_list.scm ]; then
-                    echo -e "\033[31mCannot find $GOPATH/vpcm/environment/$destnation/project/$projectname/plan_list.scm\033[0m"
-                    continue
-                fi
-                
+
                 if [ "$plan_list" == "" ]; then
                     echo -e "\033[31mCannot find any plan for project $projectname\033[0m"
                     continue
                 fi
-                
-                OLD_IFS="$IFS"
-                IFS=","
-                arr=($plan_list)
-                IFS="$OLD_IFS"
                 
                 for planname in ${arr[@]}
                 do
@@ -431,12 +357,9 @@ if [ "$action" == "publish" ]; then
                             continue
                         fi
                     fi
-                    target_plan_host=`grep $hostline $GOPATH/vpcm/environment/$destnation/project/$projectname/$planname.host`
-                    if [ "$target_plan_host" != "" ]; then
-                        publish_project $hostname $port $username $projectname $planname $tag
-                        echo $line >> $GOPATH/final_baseline.$hostname
-                        has_published_project="1"
-                    fi
+                    publish_project $hostname $port $username $projectname $planname $tag
+                    echo $line >> $GOPATH/final_baseline.$hostname
+                    has_published_project="1"
                 done
             else
                 remoteitem=`grep -E "^$projectname/" $GOPATH/baseline.$hostname`
@@ -458,23 +381,12 @@ if [ "$action" == "publish" ]; then
                 fi
                 if [ "$compare" == "1" ]; then
                     echo -e "\033[33m$projectname: $remotetag -> $tag\033[0m"
-                    if [ ! -f $GOPATH/vpcm/environment/$destnation/project/$projectname/plan_list.scm ]; then
-                        echo -e "\033[33mCannot find $GOPATH/vpcm/environment/$destnation/project/$projectname/plan_list.scm.\033[0m"
-                        continue
-                    fi
-                    plan_list=`cat $GOPATH/vpcm/environment/$destnation/project/$projectname/plan_list.scm`
-                    if [ "$plan_list" == "" ]; then
-                        echo -e "\033[33mCannot find any content in $GOPATH/vpcm/environment/$destnation/project/$projectname/plan_list.scm.\033[0m"
-                        continue
-                    fi
-                    for planname in $plan_list
+
+                    for planname in ${arr[@]}
                     do
-                        target_plan_host=`grep $hostline $GOPATH/vpcm/environment/$destnation/project/$projectname/$planname.host`
-                        if [ "$target_plan_host" != "" ]; then
-                            publish_project $hostname $port $username $projectname $planname $tag
-                            echo $line >> $GOPATH/final_baseline.$hostname
-                            has_published_project="1"
-                        fi
+                        publish_project $hostname $port $username $projectname $planname $tag
+                        echo $line >> $GOPATH/final_baseline.$hostname
+                        has_published_project="1"
                     done
                 else
                     echo -e "\033[33mSkip $projectname...\033[0m"
@@ -486,8 +398,8 @@ if [ "$action" == "publish" ]; then
         done
 
         if [ "$has_published_project" == "1" ]; then
-            toberestarted_projects=`echo $toberestarted_projects | sed 's/ /\n/g' | sort | uniq`
-            restart_project $hostname $port $username $toberestarted_projects
+            toberestarted_plans=`echo $toberestarted_plans | sed 's/ /\n/g' | sort | uniq`
+            restart_plan $hostname $port $username
             ssh -p $port -tq $username@$hostname "sudo /sbin/service nginx restart"
             echo "Merging baseline..."
             mergebaseline $GOPATH/baseline.$hostname $GOPATH/final_baseline.$hostname
@@ -499,7 +411,7 @@ if [ "$action" == "publish" ]; then
         ssh -p $port -tq $username@$hostname "rm -f $serviceroot/publish.lock"
         rm -f $GOPATH/baseline.$hostname
         rm -f $GOPATH/final_baseline.$hostname
-        toberestarted_projects=""
+        toberestarted_plans=""
     done
     echo -e "\033[32mPublishing finished.\033[0m"
 fi
